version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: calendar
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  rabbit:
    image: rabbitmq:3-management
    restart: always
    volumes:
      - ./rmq_data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  calendar:
    image: calendar:develop
    restart: always
    ports:
      - 8081:8081
      - 8082:8082
    command: ["sleep 10", "/opt/calendar/calendar"]
    depends_on:
      - db

  scheduler:
    image: scheduler:develop
    restart: always
    command: ["sleep 10", "/opt/calendar/scheduler"]
    depends_on:
      - db
      - rabbit

  sender:
    image: sender:develop
    restart: always
    command: ["sleep 10", "/opt/calendar/sender"]
    depends_on:
      - db
      - rabbit