version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: calendar
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  rabbit:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  migrations:
    image: migrations:develop
    restart: "on-failure"
    command: sh -c "sleep 5 && /migrations/migrations.sh"

  calendar:
    image: calendar:develop
    restart: on-failure
    ports:
      - 8888:8081
      - 8889:8082
    command: sh -c "sleep 10 && $$BIN_FILE --config $$CONFIG_FILE"
    depends_on:
      - db

  scheduler:
    image: scheduler:develop
    restart: on-failure
    command: sh -c "sleep 10 && $$BIN_FILE --config $$CONFIG_FILE"
    depends_on:
      - db
      - rabbit

  sender:
    image: sender:develop
    restart: on-failure
    command: sh -c "sleep 10 && $$BIN_FILE --config $$CONFIG_FILE"
    depends_on:
      - db
      - rabbit