version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: calendar
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  rabbit:
    image: rabbitmq:3-management
    restart: always
    volumes:
      - ./rmq_data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    
