log:
  level: "INFO"
storage:
  type: "sql"
  #type: "in-memory"
  db:
    name: "calendar"
    host: "arch-tc"
    user: "postgres"
    password: "postgres"
server:
  host: "0.0.0.0"
  httpPort: "8081"
  grpcPort: "8082"