log:
  level: "DEBUG"
storage:
  #type: "sql"
  type: "in-memory"
  db:
    name: "calendar"
    host: "server"
    user: "postgres"
    password: "postgres"
rmq:
  host: "server"
  port: "5672"
  user: "guest"
  password: "guest"
  queue: "e_notifications"
schedule: "10s"
