log:
  level: "DEBUG"
storage:
  type: "sql"
  #type: "in-memory"
  db:
    name: "calendar"
    host: "arch-tc"
    user: "postgres"
    password: "postgres"
rmq:
  host: "0.0.0.0"
  port: "5672"
  user: "guest"
  password: "guest"
  queue: event_notifications
schedule: "10s"
